
```yaml
name: Step 2, Add an image

# This step triggers after a commit on the branch `start-markdown`.
# This workflow updates from step 2 to step 3.

# This will run every time we create push a commit to `start-markdown`.
on:
  workflow_dispatch:
  push:
    branches:
      - start-markdown

# Permissions required for the workflow
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_commit_start_markdown_image:
    name: On commit, start markdown, image
    needs: get_current_step

    # Conditional execution:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 }}

    runs-on: ubuntu-latest

    steps:
      # Check out the repository to edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Retrieve all branches.

      # Ensure there is at least one image in the markdown file.
      - name: Check markdown syntax, image
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "\\!\\[.*\\]\\(.*\\)"

      # Update README.md to reflect step 3 instead of step 2.
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: start-markdown
```

### Explanation:
- **Trigger**: This workflow triggers on pushes to the `start-markdown` branch, ensuring it updates from step 2 to step 3.
- **Permissions**: It requires write access to repository contents to update step metadata.
- **Jobs**:
  - **get_current_step**: Checks the current step from the metadata file.
  - **on_commit_start_markdown_image**: Executes actions if the repository is not a template and the current step is 2.
    - **Steps**:
      - **Checkout**: Ensures the repository is checked out to edit `README.md`.
      - **Check markdown syntax**: Verifies there is at least one image in `index.md`.
      - **Update to step 3**: Updates the step metadata from 2 to 3 on `start-markdown` branch.

name: Step 2, Add an image

# This step triggers after a commit on the branch `start-markdown`.
# This workflow updates from step 2 to step 3.

# This will run every time we create push a commit to `start-markdown`.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - start-markdown

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_commit_start_markdown_image:
    name: On commit, start markdown, image
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      # Check that there is at least one image in the markdown file.
      - name: Check markdown syntax, image
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "\\!\\[.*\\]\\(.*\\)"

      # In README.md, switch step 2 for step 3.
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: start-markdown
